### PR TITLE
create tests for validation

### PR DESCRIPTION
**Pull request by kloud-byun**
`test_validators.py` tests for the functionality of the `validators.py`'s methods individually; covers all branches except for the callables.

`test_validations.py` is a work in progress; currently tests validators on `magql.Argument` and `magql.InputField` for the `Length` class only.

I was hoping to get some feedback on my current approach to understand if I'm proceeding correctly.

### CODE REVIEW

**Comment by kloud-byun** [comment]
mostly wanted to check if
https://github.com/autoinvent/magql/blob/b9633dd003a0541091c28d3c31d1038c8963dc81/tests/test_validations.py
is created appropriately for testing (currently only implemented testings for Argument & InputField)

**Comment by kloud-byun** [comment]
I've just checked the new update you've pushed to the main repo w/ all the documentation on validations;
Seems like I've been approaching this a lot more difficultly. I think I can definitely come up with better testings for validators now that I have the document.

**Comment by kloud-byun** [comment]
Just finished creating the test file for `test_validation_Argument.py`
Covered cases:
    *    Validation at the argument level with both built-in and custom validators
    *    Validation of nested fields (validation of "hobbies" list items)
    *    Errors when required arguments are not provided
    *    Errors when non-null fields receive null
    *    Errors when the value type does not match the expected type
    *    Errors when the username is an empty string
    *    Errors when the hobbies list is empty

Will do the same to create `test_validation_InputField.py`, `test_validation_Field.py`, and `test_validation_InputObject.py` as well.

**Comment by davidism** [comment]
I've refactored the argument tests to split the single large test into individual cases. I removed the input field test for now since it's largely a duplicate of argument and needs to go through the same refactor.

**Pull request merged**
